### ISSUE TITLE
Skewgjg

### ISSUE THREAD

**Issue by elaine011** [elaine011/test-issue#32]
as

**Comment by yarchiee** [comment]
<html>
<body>


--tw-skew-x: 6deg;
--
skew-x-12 | --tw-skew-x: 12deg;
-skew-x-12 | --tw-skew-x: -12deg;
-skew-x-6 | --tw-skew-x: -6deg;
-skew-x-3 | --tw-skew-x: -3deg;
-skew-x-2 | --tw-skew-x: -2deg;
-skew-x-1 | --tw-skew-x:


</body>
</html>

**Comment by elaine011** [comment]
new comment

**Comment by elaine011** [comment]
new comment

**Comment by elaine011** [comment]
dfd

**Comment by elaine011** [comment]
sdfs

**Comment by elaine011** [comment]
sdfsfsdfsxcv

**Comment by elaine011** [comment]
sdfsfsdfsxcv

**Comment by elaine011** [comment]
as

**Comment by elaine011** [comment]
as
